# Stage 1: Build Stage
FROM node:18-slim AS build

WORKDIR /app

COPY uachado-user/package.json /app/
RUN npm install

COPY uachado-user /app

RUN npm run build

# Stage 2: Runtime Stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
