# Stage 1: Build Stage
FROM node:18-slim AS build

WORKDIR /app

COPY uachado-user/package.json /app/
RUN npm install

COPY uachado-user /app


# Stage 2: Runtime Stage
FROM node:18-slim

COPY --from=build /app /app

EXPOSE 80

WORKDIR /app
CMD ["npm", "run", "dev", "--", "--port", "80", "--host", "0.0.0.0"]
