# Stage 1: Build Stage
FROM node:18-slim AS build

WORKDIR /app

COPY uachado-user/package.json /app/
RUN npm i

# Rest of your build process...
COPY uachado-user /app
CMD npm run build && npm run preview

