// Generated by Selenium IDE
import { Before, After, Given, When, Then } from "@cucumber/cucumber";
import { Builder, By, until } from "selenium-webdriver";

let driver;
let vars;

Before(async function () {
  driver = await new Builder().forBrowser("chrome").build();
  vars = {};
});

After(async function () {
  await driver.quit();
});

Given("I am on the landing page", async function () {
  driver = await new Builder().forBrowser("chrome").build();
  // 1 | open | / |
  await driver.get("http://localhost:3000/");
});

When("I click on the button to go to the home page", async function () {
  // 2 | click | css=.-ml-2 |
  await driver.findElement(By.css(".-ml-2")).click();
});

When("I navigate to the dropoff points page", async function () {
  // 3 | click | css=a:nth-child(1) .max-w-full |
  await driver.findElement(By.css("a:nth-child(1) .max-w-full")).click();
});

When("I select a specific dropoff point", async function () {
  // 4 | click | css=.card:nth-child(1) > .card-body .btn |
  const element = await driver.wait(
    until.elementLocated(
      By.css(".card:nth-child(1) > .card-body .btn")
    ),
    10000 // Maximum wait time in milliseconds (adjust as needed)
  );
  await element.click();
});

Then(
  "I should be able to view details about the dropoff point",
  async function () {
    const details = await driver.findElement(By.className("text-lg font-bold"));
    const detailText = await details.getText();
    if (!detailText.includes("Reitoria")) {
      throw new Error("Detail is not correct");
    }
  }
);
