name: CI Pipeline

on: 
  push:
    branches: [ main ]

jobs:

  test-and-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login on DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      

    - name: Change directory
      run: cd uachado-user
    - name: Build the Docker image
      run: docker build -t uachado/user-ui -f Dockerfile.prod .
    - name: Push image to DockerHub
      run: docker push uachado/user-ui:latest
